export const GET_REQUEST = "GET_REQUEST" ;
export const GET_ALL_VIDEOS_SUCCESS = "GET_ALL_VIDEOS_SUCCESS" ;
export const SET_CURRENT_PLAYING_VIDEO = "SET_CURRENT_PLAYING_VIDEO"
export const GET_FAILURE = "GET_FAILURE" ;